name: API CI

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - 'packages/database/**'
      - 'packages/shared/**'
      - 'packages/config/typescript/**'
      - 'pnpm-lock.yaml'

permissions:
  contents: read

jobs:
  build-main:
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, main-runner]

    strategy:
      matrix:
        node-version: [23.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            apps/api
            packages/database
            packages/shared
            packages/config/typescript
            pnpm-workspace.yaml
            pnpm-lock.yaml
            package.json
            turbo.json

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --filter=@betaversionio/api...

      - name: Set up Environment File
        env:
          PROD_ENV_FILE: ${{ secrets.PROD_ENV_FILE }}
        run: |
          echo "${{ env.PROD_ENV_FILE }}" | sed 's/\\n/\n/g' > .env

      - name: Build Application
        run: pnpm turbo build --filter=@betaversionio/api...

      - name: Start Application
        run: pm2 delete "betaversionio-api" || true && pm2 start pnpm --name "betaversionio-api" -- run --filter @betaversionio/api start:prod
