import type { IconName } from 'tech-stack-icons';

/**
 * Maps user-input tech names (lowercased) → tech-stack-icons slug.
 * Only non-obvious aliases need to be here; exact slug matches are
 * resolved automatically via the VALID set.
 */
const ALIASES: Record<string, IconName> = {
  // ── Languages ───────────────────────────────────────────────
  javascript: 'js',
  typescript: 'typescript',
  ts: 'typescript',
  python: 'python',
  java: 'java',
  csharp: 'c#',
  'c sharp': 'c#',
  cpp: 'c++',
  go: 'go',
  golang: 'go',
  rust: 'rust',
  php: 'php',
  ruby: 'ruby',
  swift: 'swift',
  kotlin: 'kotlin',
  dart: 'dart',
  scala: 'scala',
  elixir: 'elixir',
  erlang: 'erlang',
  haskell: 'haskell',
  clojure: 'clojure',
  lua: 'lua',
  ocaml: 'ocaml',
  crystal: 'crystal',
  nim: 'nim',
  solidity: 'solidity',
  bash: 'bash',
  shell: 'bash',
  'visual basic': 'visualbasic',
  vb: 'visualbasic',
  'vb.net': 'visualbasic',
  powershell: 'powershell',

  // ── Frontend Frameworks ─────────────────────────────────────
  react: 'react',
  reactjs: 'react',
  'react.js': 'react',
  'react native': 'react',
  reactnative: 'react',
  vue: 'vuejs',
  vuejs: 'vuejs',
  'vue.js': 'vuejs',
  angular: 'angular',
  angularjs: 'angular',
  svelte: 'sveltejs',
  sveltejs: 'sveltejs',
  'svelte.js': 'sveltejs',
  sveltekit: 'sveltejs',
  next: 'nextjs',
  nextjs: 'nextjs',
  'next.js': 'nextjs',
  nuxt: 'nuxtjs',
  nuxtjs: 'nuxtjs',
  'nuxt.js': 'nuxtjs',
  astro: 'astro',
  remix: 'remix',
  gatsby: 'gatsby',
  solid: 'solidjs',
  solidjs: 'solidjs',
  'solid.js': 'solidjs',
  ember: 'ember',
  emberjs: 'ember',
  'ember.js': 'ember',
  'alpine.js': 'alpinejs',
  alpinejs: 'alpinejs',
  preact: 'preact',
  qwik: 'qwik',
  lit: 'lit',
  backbone: 'backbonejs',
  backbonejs: 'backbonejs',
  'backbone.js': 'backbonejs',
  jquery: 'jquery',
  '11ty': '11ty',
  eleventy: '11ty',

  // ── CSS / Styling ──────────────────────────────────────────
  tailwind: 'tailwindcss',
  tailwindcss: 'tailwindcss',
  'tailwind css': 'tailwindcss',
  bootstrap: 'bootstrap5',
  'bootstrap 4': 'bootstrap4',
  'bootstrap 5': 'bootstrap5',
  sass: 'sass',
  scss: 'sass',
  less: 'less',
  css: 'css3',
  css3: 'css3',
  html: 'html5',
  html5: 'html5',
  'material ui': 'materialui',
  materialui: 'materialui',
  mui: 'materialui',
  'chakra ui': 'chakraui',
  chakraui: 'chakraui',
  'ant design': 'antd',
  antd: 'antd',
  bulma: 'bulmaui',
  'radix ui': 'radixui',
  radixui: 'radixui',
  shadcn: 'shadcnui',
  'shadcn/ui': 'shadcnui',
  shadcnui: 'shadcnui',
  'headless ui': 'headlessui',
  headlessui: 'headlessui',
  'panda css': 'pandacss',
  pandacss: 'pandacss',
  'element ui': 'elementui',
  elementui: 'elementui',
  'base ui': 'baseui',
  baseui: 'baseui',
  'blueprint.js': 'blueprintjs',
  blueprintjs: 'blueprintjs',
  'semantic ui': 'semanticui',
  semanticui: 'semanticui',

  // ── Backend / Runtime ──────────────────────────────────────
  node: 'nodejs',
  nodejs: 'nodejs',
  'node.js': 'nodejs',
  express: 'expressjs',
  expressjs: 'expressjs',
  'express.js': 'expressjs',
  nest: 'nestjs',
  nestjs: 'nestjs',
  'nest.js': 'nestjs',
  hono: 'hono',
  django: 'django',
  flask: 'flask',
  spring: 'spring',
  'spring boot': 'spring',
  springboot: 'spring',
  laravel: 'laravel',
  rails: 'rails',
  'ruby on rails': 'rails',
  phoenix: 'phoenix',
  codeigniter: 'codeigniter',
  '.net': 'net',
  dotnet: 'net',
  '.net core': 'netcore',
  'asp.net': 'net',
  cakephp: 'cakephp',
  deno: 'deno',
  bun: 'bunjs',
  bunjs: 'bunjs',

  // ── Databases ──────────────────────────────────────────────
  postgresql: 'postgresql',
  postgres: 'postgresql',
  mysql: 'mysql',
  mongodb: 'mongodb',
  mongo: 'mongodb',
  redis: 'redis',
  mariadb: 'mariadb',
  oracle: 'oracle',
  cassandra: 'cassandradb',
  cassandradb: 'cassandradb',
  supabase: 'supabase',
  firebase: 'firebase',
  prisma: 'prisma',
  drizzle: 'drizzle',
  mongoose: 'mongoose',
  elasticsearch: 'elastic',
  elastic: 'elastic',
  faunadb: 'faunadb',
  fauna: 'faunadb',
  clickhouse: 'clickhouse',
  neon: 'neon',
  convex: 'convex',

  // ── Cloud / Hosting ────────────────────────────────────────
  aws: 'aws',
  'amazon web services': 'aws',
  gcp: 'gcloud',
  'google cloud': 'gcloud',
  gcloud: 'gcloud',
  azure: 'azure',
  'microsoft azure': 'azure',
  vercel: 'vercel',
  netlify: 'netlify',
  cloudflare: 'cloudflare',
  digitalocean: 'digitalocean',
  'digital ocean': 'digitalocean',
  heroku: 'heroku',
  railway: 'railway',
  render: 'render',
  'fly.io': 'flyio',
  flyio: 'flyio',
  replit: 'replit',

  // ── DevOps / Infra ─────────────────────────────────────────
  docker: 'docker',
  kubernetes: 'kubernetes',
  k8s: 'kubernetes',
  terraform: 'terraform',
  apache: 'apache',
  grafana: 'grafana',
  prometheus: 'prometheus',
  datadog: 'datadog',
  sentry: 'sentry',
  serverless: 'serverless',

  // ── CI / CD ────────────────────────────────────────────────
  'github actions': 'github',
  'gitlab ci': 'gitlab',
  circleci: 'circleci',

  // ── Version Control ────────────────────────────────────────
  git: 'git',
  github: 'github',
  gitlab: 'gitlab',
  bitbucket: 'bitbucket',

  // ── Testing ────────────────────────────────────────────────
  jest: 'jest',
  vitest: 'vitest',
  cypress: 'cypress',
  playwright: 'playwright',
  mocha: 'mochajs',
  mochajs: 'mochajs',
  'ava.js': 'avajs',
  avajs: 'avajs',

  // ── Mobile ─────────────────────────────────────────────────
  flutter: 'flutter',
  expo: 'expo',
  ionic: 'ionic',
  xamarin: 'xamarin',
  android: 'android',

  // ── Build Tools / Package Managers ─────────────────────────
  webpack: 'webpack',
  vite: 'vitejs',
  vitejs: 'vitejs',
  esbuild: 'esbuild',
  rollup: 'rollup',
  babel: 'babel',
  npm: 'npm',
  turborepo: 'turborepo',
  turbopack: 'turborepo',
  eslint: 'eslint',
  prettier: 'prettier',
  'biome.js': 'biomejs',
  biomejs: 'biomejs',
  biome: 'biomejs',

  // ── API / Data ─────────────────────────────────────────────
  graphql: 'graphql',
  swagger: 'swagger',
  postman: 'postman',
  'socket.io': 'socketio',

  // ── Design / Tools ─────────────────────────────────────────
  figma: 'figma',
  sketch: 'sketch',
  storybook: 'storybook',
  vscode: 'vscode',
  'vs code': 'vscode',
  'visual studio code': 'vscode',
  neovim: 'neovim',
  vim: 'vim',
  cursor: 'cursor',
  electron: 'electron',
  'three.js': 'threejs',
  threejs: 'threejs',
  'gsap': 'gsap',
  'framer': 'framer',
  'framer motion': 'framer',

  // ── Payments / Auth / SaaS ─────────────────────────────────
  stripe: 'stripe',
  auth0: 'auth0',
  clerk: 'clerk',
  linear: 'linear',
  notion: 'notion',
  slack: 'slack',
  jira: 'jira',
  twilio: 'twilio',
  resend: 'resend',
  posthog: 'posthog',

  // ── CMS ────────────────────────────────────────────────────
  wordpress: 'wordpress',
  payload: 'payload',
  'payload cms': 'payload',

  // ── AI / ML ────────────────────────────────────────────────
  openai: 'openai',
  'gpt': 'openai',
  claude: 'claude',
  anthropic: 'anthropic',
  pytorch: 'pytorch',
  langchain: 'langchain',
  'hugging face': 'huggingface',
  huggingface: 'huggingface',
  gemini: 'gemini',
  mistral: 'mistral',
  groq: 'groq',
  deepseek: 'deepseek',
  'stability ai': 'stability',
  stability: 'stability',
  'dall-e': 'dalle',
  dalle: 'dalle',

  // ── Misc ───────────────────────────────────────────────────
  webassembly: 'webassembly',
  wasm: 'webassembly',
  pwa: 'pwa',
  markdown: 'markdown',
  json: 'json',
  zod: 'zod',
  tanstack: 'tanstack',
  'react query': 'reactquery',
  reactquery: 'reactquery',
  'react router': 'reactrouter',
  reactrouter: 'reactrouter',
  redux: 'redux',
  'redux saga': 'reduxsaga',
  pinia: 'pinia',
  i18next: 'i18next',
  n8n: 'n8n',
  zapier: 'zapier',
  airtable: 'airtable',
  linux: 'linux',
  ubuntu: 'ubuntu',
  chrome: 'chrome',
  firefox: 'firefox',
  appwrite: 'appwrite',
  algolia: 'algolia',
  cloudinary: 'cloudinary',
  hugo: 'hugo',
  docusaurus: 'docusaurus',
  hexo: 'hexo',
  homebrew: 'homebrew',
  insomnia: 'insomnia',
};

/**
 * Resolve a user-input tech name to a valid `IconName` for tech-stack-icons.
 * Returns `null` when no match is found.
 */
export function getTechIconName(tech: string): IconName | null {
  const key = tech.toLowerCase().trim();
  return ALIASES[key] ?? null;
}
