name: Web CI

on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/**'
      - 'packages/shared/**'
      - 'packages/config/typescript/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/web.yaml'

permissions:
  contents: read

jobs:
  build-main:
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, main-runner, web]

    strategy:
      matrix:
        node-version: [23.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            apps/web
            packages/shared
            packages/config/typescript
            pnpm-workspace.yaml
            pnpm-lock.yaml
            package.json
            turbo.json
            .npmrc

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --filter=@betaversionio/web...

      - name: Set up Environment File
        env:
          WEB_ENV_FILE: ${{ secrets.WEB_ENV_FILE }}
        run: echo "$WEB_ENV_FILE" > apps/web/.env

      - name: Build Application
        run: pnpm turbo build --filter=@betaversionio/web...

      - name: Start Application
        run: pm2 restart "betaversionio-web" || pm2 start pnpm --name "betaversionio-web" -- run --filter @betaversionio/web start
